In [1]:
from cities.utils import data_grabber
import matplotlib.pyplot as plt
import pandas as pd
# import geopandas as gpd

In [3]:
# # Save the area of each county in the US
# url = "https://www2.census.gov/geo/tiger/GENZ2021/shp/cb_2021_us_county_20m.zip"
# counties = gpd.read_file(url)
# counties = counties[["GEOID", "NAME", "STATE_NAME", "ALAND", "AWATER"]]
# counties.head()
# counties.to_csv("../../../../cities/data/raw/counties_area.csv")

# https://www.census.gov/library/publications/2011/compendia/usa-counties-2011.html#LND

LND010190D

In [93]:
counties_area = pd.read_csv("../../../../cities/data/raw/LND01.csv")
population = pd.read_csv("../../../../cities/data/processed/population_wide.csv")

# 5-digit FIPS code
counties_area['GeoFIPS'] = counties_area['STCOU'].astype(str).str.zfill(5)
population['GeoFIPS'] = population['GeoFIPS'].astype(str).str.zfill(5)

counties_area['area_sqm'] = counties_area['LND010190D']

population_density = population.copy()

# compute population density 
for index, row in population.iterrows():
    geofips = row['GeoFIPS']
    area_row = counties_area[counties_area['GeoFIPS'] == geofips]['area_sqm']
    if area_row.size == 0:
        print('No area found for {}'.format(geofips))
    else:
        # iterate over all year columns
        for col in population.columns[2:]:
            tmp = row[col] / area_row.astype(float)
            population_density.loc[index, col] = tmp.iloc[0]


# population_density.to_csv("../../../../cities/data/processed/population_density_wide.csv")
population_density

No area found for 02158
No area found for 46102

,GeoFIPS,GeoName,1993,1994,1995,1996,1997,1998,1999,2000,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,01001,"Autauga, AL",61.130871,63.170607,64.702476,66.513921,68.219491,69.655412,71.073136,72.823372,...,91.908882,91.968436,92.696323,93.099969,94.218267,94.908104,95.498685,96.353951,97.399461,97.760095
1,01003,"Baldwin, AL",54.963790,57.503897,59.640468,61.868303,64.212562,66.323973,67.858693,69.726898,...,94.195098,96.723859,99.038518,101.093691,103.599266,106.243957,109.088936,112.022712,115.012728,118.048622
2,01005,"Barbour, AL",30.257907,30.677987,30.791850,31.282681,31.412021,31.882952,31.910589,32.075305,...,30.201528,30.022441,29.895312,29.442068,28.982191,28.308958,28.056910,27.863452,27.835815,27.597033
3,01007,"Bibb, AL",28.388489,28.861711,29.587530,30.191847,30.996003,31.736211,32.869704,31.835332,...,36.262190,36.041567,36.108713,36.142286,36.217426,36.140687,35.784173,35.819345,35.528377,35.934452
4,01009,"Blount, AL",64.344886,65.350035,67.716898,69.690310,72.319988,75.038807,77.210482,78.547606,...,88.921847,89.178514,89.215400,89.399831,89.507416,90.180589,90.317375,90.610928,90.803043,90.741566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3069,56037,"Sweetwater, WY",3.818817,3.808714,3.798134,3.741709,3.691288,3.675752,3.635435,3.579200,...,4.280419,4.290046,4.266503,4.240673,4.191778,4.124868,4.075114,4.044519,4.018212,3.966362
3070,56039,"Teton, WY",3.252755,3.391790,3.530825,3.669859,3.832817,3.998854,4.185734,4.353665,...,5.118949,5.278828,5.385413,5.448180,5.484893,5.511658,5.479446,5.505026,5.529896,5.583899
3071,56041,"Uinta, WY",9.379401,9.545137,9.524539,9.549448,9.548969,9.593995,9.532683,9.420116,...,10.086892,10.078269,10.024621,10.006898,9.985342,9.869423,9.807632,9.768353,9.791345,9.884272
3072,56043,"Washakie, WY",3.768420,3.782687,3.794725,3.776891,3.803643,3.827719,3.756381,3.679247,...,3.738993,3.736763,3.669884,3.666763,3.616827,3.538355,3.477718,3.445616,3.414406,3.435361
3073,56045,"Weston, WY",2.744435,2.789849,2.800265,2.819847,2.801932,2.807765,2.777766,2.761100,...,2.954007,2.980255,2.984005,3.014837,3.028586,2.919842,2.894427,2.890677,2.836930,2.810264

In [41]:
population[population['GeoFIPS'] == 49700]
counties_area[counties_area['GEOID'] == '49700']

Empty DataFrame
Columns: [Unnamed: 0, GEOID, NAME, STATE_NAME, ALAND, AWATER]
Index: []

In [81]:
geofips

1001

In [42]:
counties_area['GEOID']

0       13239
1       18111
2       19053
3       24013
4       29155
        ...
3216    41063
3217    13163
3218     2100
3219     5117
3220    47025
Name: GEOID, Length: 3221, dtype: int64